import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Random;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class PasswordGenerator {

    private static final String numbers = "1234567890";
    private static final String letters = "abcdefghijklmnopqrstuvwxyz";
    private static final String special = "+%^&*()?+";

    public String createStringOfRandomCharacters() {
        List<String> characterTypeList = new ArrayList<>();
        characterTypeList.add(numbers);
        characterTypeList.add(letters);
        characterTypeList.add(special);

        Collections.shuffle(characterTypeList);

        String randomCharacters = "";

        randomCharacters += pickCharactersFromList(1, characterTypeList.get(0));
        randomCharacters += pickCharactersFromList(1, characterTypeList.get(1));
        randomCharacters += pickCharactersFromList(1, characterTypeList.get(2));

        return randomCharacters;
    }

    public String pickCharactersFromList(int numberAmount, String alphabet) {
        int N = alphabet.length();
        String character = "";
        Random r = new Random();

        for (int i = 0; i < numberAmount; i++) {
           character += alphabet.charAt(r.nextInt(N));
        }

        character = shuffle(character);
        return  character;
    }

    public String shuffle (String orderedPassword) {

        List<Character> chars = new ArrayList<>();

        for (char ch: orderedPassword.toCharArray()){
            chars.add(ch);
        }

        Collections.shuffle(chars);

        String newPassword = "";
        for (char ch: chars) {
            newPassword+= ch;
        }

        return newPassword;
    }

//    public String findPassword() {
//
//        String numbers = ("1234567890");
//        String letters = ("abcdefghijklmnopqrstuvwxyz");
//        String specials = ("£$!#@+-/*");
//        ArrayList<Character> charactersList = new ArrayList<>();
//        String password = "";
//
//        Random r = new Random();
//
//        for (int i = 0; i < 2; i++) {
//            password += numbers.charAt(r.nextInt(numbers.length()));
//        }
//        for (int i = 0; i < 2; i++) {
//            password += letters.charAt(r.nextInt(letters.length()));
//        }
//        for (int i = 0; i < 2; i++) {
//            password += specials.charAt(r.nextInt(specials.length()));
//        }
//
//        for (char number: numbers.toCharArray()){
//            charactersList.add(number);
//        }
//
//        for (char letter: letters.toCharArray()){
//            charactersList.add(letter);
//        }
//
//        for (char special: specials.toCharArray()){
//            charactersList.add(special);
//        }
//
//        return password;
//

//
//        BCryptPasswordEncoder bCryptPasswordEncoder = new BCryptPasswordEncoder();

//        return bCryptPasswordEncoder.encode (Collections.shuffle(randomPassword));


//        System.out.println(randomPassword);
//
//        return randomPassword;


}
